export type { ThemeState } from './redux/themeSlice'
export { themeActions, themeReducer } from './redux/themeSlice'
export type { ThemeProviderProps } from './ThemeProvider'
export { configureSplashScreen, ThemeProvider } from './ThemeProvider'
export type { ComputedThemeOptions, ThemeAppearance } from './useComputedTheme'
export { useComputedTheme } from './useComputedTheme'
export { getBlendedColor } from './utils/getBlendedColor'
export { getHex } from './utils/getHex'
export type { RGB } from './utils/getRgb'
export { getRgb } from './utils/getRgb'
export type { TriadicPalette } from './utils/getTriadicPalette'
export { getTriadicPalette } from './utils/getTriadicPalette'
export { isDarkColor } from './utils/isDarkColor'
